// This file is generated by Slice Machine. Update with care!

import NavigationItem from './NavigationItem';

export {
	NavigationItem,
};

export const components = {
	navigation_item: NavigationItem,
};
